### ISSUE TITLE
`--package=NAME` option is broken

### ISSUE THREAD

**Issue by vlaci** [svanderburg/composer2nix#7]
The following example from the README fails to build:
```
$ composer2nix -p phpunit/phpunit
error: expression does not evaluate to a derivation (or a set or list of those)
sh: /bin/composer: No such file or directory
```
I have narrowed it down to the change in `composer` derivation introduced in
https://github.com/svanderburg/composer2nix/commit/cce1630d5bcd15f41852d54c90be0f3746c3c9cf#diff-68e0289af86f9a9377d4f5a9bd4e0833R267 :
```
$ nix-build --no-out-link -E 'let pkgs = import <nixpkgs> {}; composerEnv = import ./composer-env.nix { inherit (pkgs) stdenv writeTextFile fetchurl php unzip; }; in composerEnv.composer'
error: expression does not evaluate to a derivation (or a set or list of those)
```

**Comment by svanderburg** [comment]
I have not been able to reproduce this error, but in 4fe6f66ecbf84d2e546876a43af17bab37439da6 I have replaced that ugly command invocation by something that installs composer from Nixpkgs. That should most likely solve your case.

**Comment by svanderburg** [comment]
I assume this problem is solved by the above fix. Closing this. Feel free to reopen if it still doesn't work.
